[tool.black]
line-length = 100
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
src/api/v1/schedule/schemas/generated_schemas.py|
src/grpc/schedule_pb2.py|
src/grpc/schedule_pb2_grpc.py
'''

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]

[tool.ruff]
line-length = 100
exclude = [
    "src/api/v1/schedule/schemas/generated_schemas.py",
    "src/grpc/schedule_pb2.py",
    "src/grpc/schedule_pb2_grpc.py",
    "docs",
    "alembic",
]
