# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-04-22T20:22:33+00:00

from __future__ import annotations

from datetime import datetime, timedelta
from typing import List, Optional, Union
from uuid import UUID

from pydantic import BaseModel, Field, PositiveInt


class SGetNextTakingsResponse(BaseModel):
    end_date: Optional[datetime] = Field(
        None, description='timezone is always UTC', title='End Date'
    )
    frequency: PositiveInt = Field(..., title='Frequency')
    medicine_name: str = Field(..., title='Medicine Name')
    next_taking_time: datetime = Field(..., title='Next Taking Time')
    start_date: Optional[datetime] = Field(
        None, description='timezone is always UTC', title='Start Date'
    )


class SGetScheduleResponse(BaseModel):
    end_date: Optional[datetime] = Field(
        None, description='timezone is always UTC', title='End Date'
    )
    frequency: PositiveInt = Field(..., title='Frequency')
    medicine_name: str = Field(..., title='Medicine Name')
    start_date: Optional[datetime] = Field(
        None, description='timezone is always UTC', title='Start Date'
    )


class SScheduleCreateRequest(BaseModel):
    duration: Optional[timedelta] = Field(None, title='Duration')
    end_date: Optional[datetime] = Field(
        None, description='timezone is always UTC', title='End Date'
    )
    frequency: PositiveInt = Field(..., title='Frequency')
    medicine_name: str = Field(..., title='Medicine Name')
    medicine_policy: PositiveInt = Field(..., title='Medicine Policy')
    name: Optional[str] = Field(None, title='Name')
    start_date: Optional[datetime] = Field(
        None, description='timezone is always UTC', title='Start Date'
    )


class SScheduleCreateResponse(BaseModel):
    id: UUID = Field(..., title='Id')


class SuccessResponseSchemaSGetScheduleResponse(BaseModel):
    data: SGetScheduleResponse
    error: Optional[str] = Field(None, title='Error')
    success: Optional[bool] = Field(True, title='Success')


class SuccessResponseSchemaSScheduleCreateResponse(BaseModel):
    data: SScheduleCreateResponse
    error: Optional[str] = Field(None, title='Error')
    success: Optional[bool] = Field(True, title='Success')


class SuccessResponseSchemaListSGetNextTakingsResponse(BaseModel):
    data: List[SGetNextTakingsResponse] = Field(..., title='Data')
    error: Optional[str] = Field(None, title='Error')
    success: Optional[bool] = Field(True, title='Success')


class SuccessResponseSchemaListUUID(BaseModel):
    data: List[UUID] = Field(..., title='Data')
    error: Optional[str] = Field(None, title='Error')
    success: Optional[bool] = Field(True, title='Success')


class ValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')
