"""Make medicine_policy unique

Revision ID: 9ffcf246c433
Revises: fa575b6aba1a
Create Date: 2025-04-26 20:58:35.553433

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ffcf246c433"
down_revision: Union[str, None] = "fa575b6aba1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "schedules", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    op.create_unique_constraint(None, "users", ["medicine_policy"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "schedules", type_="unique")
    # ### end Alembic commands ###
