openapi: 3.1.0
x-stoplight:
  id: oamjvuvfd6wmi
info:
  title: kd-schedule
  version: 0.1.0
components:
  schemas:
    ResponseSchema:
      type: object
      properties:
        success:
          type: boolean
          title: Success
        error:
          type: string
          nullable: true
          title: Error
      required:
        - success
      title: ResponseSchema
      x-stoplight:
        id: q5e86jay8yoff
    SuccessResponseSchema:
      allOf:
        - $ref: '#/components/schemas/ResponseSchema'
        - type: object
          properties:
            success:
              type: boolean
              default: true
          title: SuccessResponseSchema
      x-stoplight:
        id: tcs5iahh4xwus
    ErrorResponseSchema:
      allOf:
        - $ref: '#/components/schemas/ResponseSchema'
        - type: object
          properties:
            success:
              type: boolean
              default: false
            data:
              nullable: true
          title: ErrorResponseSchema
      x-stoplight:
        id: nizy02gzhpwg3
    SuccessResponse_SGetScheduleResponse:
      allOf:
        - $ref: '#/components/schemas/SuccessResponseSchema'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/SGetScheduleResponse'
          required:
            - data
      title: SuccessResponse_SGetScheduleResponse
      x-stoplight:
        id: 8na9viqr3cxoa
    SuccessResponse_SScheduleCreateResponse:
      allOf:
        - $ref: '#/components/schemas/SuccessResponseSchema'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/SScheduleCreateResponse'
          required:
            - data
      title: SuccessResponse_SScheduleCreateResponse
      x-stoplight:
        id: 1ej8f4vfqvk29
    SuccessResponse_List_SGetNextTakingsResponse:
      allOf:
        - $ref: '#/components/schemas/SuccessResponseSchema'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/SGetNextTakingsResponse'
              title: Data
          required:
            - data
      title: SuccessResponse_List_SGetNextTakingsResponse
      x-stoplight:
        id: c4ou4uyk78r12
    SuccessResponse_List_UUID:
      allOf:
        - $ref: '#/components/schemas/SuccessResponseSchema'
        - type: object
          properties:
            data:
              type: array
              items:
                type: string
                format: uuid
              title: Data
          required:
            - data
      title: SuccessResponse_List_UUID
      x-stoplight:
        id: kmvdvg26ahb1p
    HTTPValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
      title: HTTPValidationError
      x-stoplight:
        id: b7nzivr74u6qg
    ValidationError:
      type: object
      properties:
        loc:
          type: array
          items:
            oneOf:
              - type: string
              - type: integer
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      required:
        - loc
        - msg
        - type
      title: ValidationError
      x-stoplight:
        id: ybdv6pqy7qe9i
    SGetNextTakingsResponse:
      type: object
      properties:
        end_date:
          type: string
          format: date-time
          nullable: true
          description: timezone is always UTC
          title: End Date
        frequency:
          type: integer
          exclusiveMinimum: 0.0
          title: Frequency
        medicine_name:
          type: string
          title: Medicine Name
        next_taking_time:
          type: string
          format: date-time
          title: Next Taking Time
        start_date:
          type: string
          format: date-time
          nullable: true
          description: timezone is always UTC
          title: Start Date
      required:
        - medicine_name
        - frequency
        - next_taking_time
      title: SGetNextTakingsResponse
      x-stoplight:
        id: g08i1525fzw6p
    SGetScheduleResponse:
      type: object
      properties:
        end_date:
          type: string
          format: date-time
          nullable: true
          description: timezone is always UTC
          title: End Date
        frequency:
          type: integer
          exclusiveMinimum: 0.0
          title: Frequency
        medicine_name:
          type: string
          title: Medicine Name
        start_date:
          type: string
          format: date-time
          nullable: true
          description: timezone is always UTC
          title: Start Date
      required:
        - medicine_name
        - frequency
      title: SGetScheduleResponse
      x-stoplight:
        id: 1gxvb58x72y8x
    SScheduleCreateRequest:
      type: object
      properties:
        duration:
          type: string
          format: duration
          nullable: true
          title: Duration
        end_date:
          type: string
          format: date-time
          nullable: true
          description: timezone is always UTC
          title: End Date
        frequency:
          type: integer
          exclusiveMinimum: 0.0
          title: Frequency
        medicine_name:
          type: string
          title: Medicine Name
        medicine_policy:
          type: integer
          exclusiveMinimum: 0.0
          title: Medicine Policy
        name:
          type: string
          nullable: true
          title: Name
        start_date:
          type: string
          format: date-time
          nullable: true
          description: timezone is always UTC
          title: Start Date
      required:
        - medicine_policy
        - medicine_name
        - frequency
      title: SScheduleCreateRequest
      x-stoplight:
        id: kduiufasahxx1
    SScheduleCreateResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          title: Id
      required:
        - id
      title: SScheduleCreateResponse
      x-stoplight:
        id: fg5uw5ugm5kn0
paths:
  /api/v1/next_takings:
    get:
      description: 'Get next takings for a user. If next_takings is provided, it will use it instead of the default value from the config.'
      operationId: get_next_takings_api_v1_next_takings_get
      parameters:
        - description: medicine policy number of user
          in: query
          name: user_id
          required: true
          schema:
            type: integer
            exclusiveMinimum: 0.0
            title: User Id
        - description: Optional manual next_taking interval
          in: query
          name: next_takings
          required: false
          schema:
            type: string
            format: duration
            default: PT1H
            title: Next Takings
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse_List_SGetNextTakingsResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Next Takings
      tags:
        - schedule
      x-stoplight:
        id: gp49hqrytnlit
  /api/v1/schedule:
    get:
      description: Get a schedule by id.
      operationId: get_schedule_api_v1_schedule_get
      parameters:
        - description: medicine policy number of user
          in: query
          name: user_id
          required: true
          schema:
            type: integer
            exclusiveMinimum: 0.0
            title: User Id
        - description: schedule unique UUID
          in: query
          name: schedule_id
          required: true
          schema:
            type: string
            format: uuid
            title: Schedule Id
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse_SGetScheduleResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Schedule
      tags:
        - schedule
      x-stoplight:
        id: qt60yn41x1r3b
    post:
      description: 'Create a new schedule for a user. If user is not registered, it will be registered first. If end_time and duration are provided, it will use end_time. If only duration is provided, it will use current time + duration. If start_date is provided, it will use start_date.'
      operationId: create_schedule_api_v1_schedule_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SScheduleCreateRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse_SScheduleCreateResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Create Schedule
      tags:
        - schedule
      x-stoplight:
        id: xnquo7wwh3y4a
  /api/v1/schedules:
    get:
      description: Get all schedules ids for a user.
      operationId: get_schedules_ids_api_v1_schedules_get
      parameters:
        - description: medicine policy number of user
          in: query
          name: user_id
          required: true
          schema:
            type: integer
            exclusiveMinimum: 0.0
            title: User Id
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse_List_UUID'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Schedules Ids
      tags:
        - schedule
      x-stoplight:
        id: w5zzei1mkzym8
