name: Test and lint

on:
  push:
    branches: [main, feat-tests]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint (Ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-ci.yml
        with:
          dependencies: ruff
      - name: Run ruff
        run: ruff check .

  format:
    name: Check formatting (Black)
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-ci.yml
        with:
          dependencies: black
      - name: Run black
        run: black --check .

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-ci.yml
        with:
          dependencies: pytest pytest-asyncio
      - name: Run tests
        run: pytest