name: Generate schemas from OpenAPI (docs/openapi.yaml)

on:
  push:
    paths:
      - 'docs/openapi.yaml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: 1
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          python-version-file: 'pyproject.toml'
          
      - name: Install dependencies
        run: uv pip install datamodel-code-generator
          
      - name: Generate models from OpenAPI
        run: |
          datamodel-codegen --input docs/openapi.yaml --output src/api/v1/schedule/schemas/generated_schemas.py --disable-timestamp
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update generated schemas from OpenAPI"
          title: "Update generated schemas from OpenAPI"
          branch: update-schemas-${{ github.run_id }}
          base: main
          labels: |
            automated-pr
            openapi-update